name: Production

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
  IMAGE1: test-app-1
  IMAGE2: test-app-2
  RUN_REGION: us-central1

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      # https://github.com/GoogleCloudPlatform/github-actions/blob/master/example-workflows/cloud-run/.github/workflows/cloud-run.yml
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.SA_KEY }}
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}

      # Configure gcloud CLI
      - name: gcloud Setup
        run: |-
          gcloud auth configure-docker

      # https://www.learncloudnative.com/blog/2020-02-20-github-action-build-push-docker-images/
      - name: Build Images
        run: |-
          echo "gcr.io/$PROJECT_ID/$IMAGE1:$GITHUB_SHA" && \
          docker build \
            -t "gcr.io/$PROJECT_ID/$IMAGE1:$GITHUB_SHA" \
            -t "gcr.io/$PROJECT_ID/$IMAGE1:latest" \
            -t "gcr.io/$PROJECT_ID/$IMAGE2:$GITHUB_SHA" \
            -t "gcr.io/$PROJECT_ID/$IMAGE2:latest" .

      - name: Push Images
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE1:$GITHUB_SHA" \
          && docker push "gcr.io/$PROJECT_ID/$IMAGE1:latest" \
          && docker push "gcr.io/$PROJECT_ID/$IMAGE2:latest" \
          && docker push "gcr.io/$PROJECT_ID/$IMAGE2:latest"

      - name: Deploy
        run: |-
          gcloud run deploy "$IMAGE1" \
            --quiet \
            --region "$REGION" \
            --async \
            --image "gcr.io/$PROJECT_ID/$IMAGE1:$GITHUB_SHA" \
            && gcloud run deploy "$IMAGE2" \
            --quiet \
            --region "$REGION" \
            --async \
            --image "gcr.io/$PROJECT_ID/$IMAGE2:$GITHUB_SHA"