name: Production

on:
  push:
    branches:
      - master


jobs:
  push:
    name: Run
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
      APP1: test-app-1
      APP2: test-app-2
      REGION: us-central1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      # https://github.com/GoogleCloudPlatform/github-actions/blob/master/example-workflows/cloud-run/.github/workflows/cloud-run.yml
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.SA_KEY }}
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}

      # Configure gcloud CLI
      - name: gcloud Setup
        run: |-
          gcloud auth configure-docker

      # https://www.learncloudnative.com/blog/2020-02-20-github-action-build-push-docker-images/
      - name: Build Images
        run: |-
          echo "gcr.io/$PROJECT_ID/$APP1:$GITHUB_SHA" && \
          docker build \
            -t "gcr.io/$PROJECT_ID/$APP1:$GITHUB_SHA" \
            -t "gcr.io/$PROJECT_ID/$APP1:latest" \
            -t "gcr.io/$PROJECT_ID/$APP2:$GITHUB_SHA" \
            -t "gcr.io/$PROJECT_ID/$APP2:latest" .

      - name: Push Images
        run: |-
          docker push "gcr.io/$PROJECT_ID/$APP1:$GITHUB_SHA" \
          && docker push "gcr.io/$PROJECT_ID/$APP1:latest" \
          && docker push "gcr.io/$PROJECT_ID/$APP2:latest" \
          && docker push "gcr.io/$PROJECT_ID/$APP2:latest"

      - name: Deploy
        run: |-
          gcloud run deploy ${{ env.APP1 }} \
            --quiet \
            --region ${{ env.REGION }} \
            --async \
            --image "gcr.io/$PROJECT_ID/$APP1:$GITHUB_SHA" \
            --platform managed \
            && gcloud run deploy ${{ env.APP2 }} \
            --quiet \
            --region ${{ env.REGION }} \
            --async \
            --image "gcr.io/$PROJECT_ID/$APP2:$GITHUB_SHA" \
            --platform managed